language: python
cache: pip
python:
  - "2.7"
  - "3.6"
# workaround to make boto work on travis
# from https://github.com/travis-ci/travis-ci/issues/7940
before_install:
  - sudo rm -f /etc/boto.cfg
install:
  - pip install -r requirements/test.txt
script:
  - pytest -rs
